apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo
spec:
  containers:
  - name: mongo-db
    image: mongo
    ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    name: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
  labels:
    app: todo-app
spec:
  containers:
  - name: todo-app
    image: mathur98/todo-app:1.0
    ports:
        - containerPort: 5000
    env:
    - name: MONGO_HOST
      value: "mongo-service"
    - name: MONGO_PORT
      value: "27017"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 5000  # Port your Flask app is listening on
  type: LoadBalancer