version: '1'
services:
  web:
    build: .
    ports:
     - "8080:5000"
    environment:
     - MONGO_HOST=db
     - MONGO_PORT=27017
    depends_on:
     - db
  db:
    image: mongo
    volumes:
     - mongodb_data:/data/db
volumes:
  mongodb_data:
