apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-app
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: mathur98/todo-app:1.2
          ports:
            - containerPort: 5000
          env:
          - name: MONGO_HOST
            value: "mongo-service"
          - name: MONGO_PORT
            value: "27017"
          # liveness probe
          livenessProbe:
            httpGet:
              path: /healthtrack 
              port: 5000       
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          # readiness probe
          readinessProbe:
            httpGet:
              path: /list  
              port: 5000         
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 5000  # Port your Flask app is listening on
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-db-app-rc
spec:
  replicas: 2
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-app-rc
spec:
  replicas: 1
  selector:
    app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: mathur98/todo-app:1.1
          ports:
            - containerPort: 5000
          env:
          - name: MONGO_HOST
            value: "mongo-service"
          - name: MONGO_PORT
            value: "27017"